server:
  port: 11121

spring:
  application:
    name: test-service
    #cloud注册中心
    cloud:
      consul:
        host: localhost
        port: 8500


#eureka注册中心
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8081/eureka/
