server:
  port: 2222

spring:
  application:
    name: consumer

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false
#http://stackoverflow.com/questions/43088585/spring-cloud-feign-hystrix-fallback-not-work
feign:
  hystrix:
    enabled: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8081/eureka/
