server:
  port: 2222

spring:
  application:
    name: consumer

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8081/eureka/
